//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit_t()
        {
            this.Product_t = new HashSet<Product_t>();
        }
    
        public int unit_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
        public Nullable<System.DateTime> creation_Date { get; set; }
        public string last_user_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_t> Product_t { get; set; }
    }
}
