//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_t
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name_1 { get; set; }
        public string last_name_2 { get; set; }
        public int identification { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> hiring_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
        public Nullable<System.DateTime> creation_Date { get; set; }
        public string last_user_update { get; set; }
    
        public virtual User_t User_t { get; set; }
        public virtual Warehouse_t Warehouse_t { get; set; }
    }
}
