//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventorySystemEntities : DbContext
    {
        public InventorySystemEntities()
            : base("name=InventorySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_t> Category_t { get; set; }
        public virtual DbSet<Employee_t> Employee_t { get; set; }
        public virtual DbSet<Product_t> Product_t { get; set; }
        public virtual DbSet<Role_t> Role_t { get; set; }
        public virtual DbSet<Unit_t> Unit_t { get; set; }
        public virtual DbSet<User_t> User_t { get; set; }
        public virtual DbSet<Warehouse_t> Warehouse_t { get; set; }
        public virtual DbSet<inventario_v> inventario_v { get; set; }
    }
}
