
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventorySystem.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class inventario_v
{

    public string Producto { get; set; }

    public string Almacen { get; set; }

    public string Categoria { get; set; }

}

}
