
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventorySystem.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class Sell_t
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sell_t()
    {

        this.Operation_t = new HashSet<Operation_t>();

    }


    public int Id { get; set; }

    public double total { get; set; }

    public double cash { get; set; }

    public double discount { get; set; }

    public int Person_Id { get; set; }

    public int Operation_type_Id { get; set; }

    public Nullable<int> user_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Operation_t> Operation_t { get; set; }

    public virtual Operation_type_t Operation_type_t { get; set; }

    public virtual Person_t Person_t { get; set; }

    public virtual User_t User_t { get; set; }

}

}
