
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventorySystem.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class User_t
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User_t()
    {

        this.Employee_t = new HashSet<Employee_t>();

        this.Sell_t = new HashSet<Sell_t>();

    }


    public int user_id { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public Nullable<int> role_id { get; set; }

    public Nullable<System.DateTime> last_update_date { get; set; }

    public Nullable<System.DateTime> creation_Date { get; set; }

    public string last_user_update { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee_t> Employee_t { get; set; }

    public virtual Role_t Role_t { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sell_t> Sell_t { get; set; }

}

}
